# Generated by Django 3.1.2 on 2020-10-14 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybl', '0003_auto_20201014_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='bPost',
        ),
    ]
