# Generated by Django 3.1.2 on 2020-10-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0004_auto_20201014_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='topic',
            new_name='bPost',
        ),
    ]
