# Generated by Django 3.1.2 on 2020-10-16 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0006_auto_20201014_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
