# Generated by Django 3.1.2 on 2020-10-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0007_bpost_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpost',
            old_name='text',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='bpost',
            old_name='body',
            new_name='main',
        ),
    ]
