# Generated by Django 3.1.2 on 2020-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0008_auto_20201016_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('change', models.FloatField()),
            ],
        ),
    ]
