# Generated by Django 3.1.2 on 2020-11-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0011_auto_20201111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
