# Generated by Django 3.1.2 on 2020-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0012_auto_20201116_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='val_noexp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
