# Generated by Django 3.1.2 on 2020-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0013_lang_val_noexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='res_vac',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
