# Generated by Django 3.1.2 on 2020-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0014_lang_res_vac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('val', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
