# Generated by Django 3.1.2 on 2020-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0015_tickers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickers',
            new_name='Ticker',
        ),
    ]
