# Generated by Django 3.1.2 on 2020-12-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0016_auto_20201130_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='val',
            new_name='sp500',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='name',
        ),
    ]
