# Generated by Django 3.1.2 on 2020-12-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0018_auto_20201202_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='sp50',
        ),
    ]
