# Generated by Django 3.1.2 on 2020-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0019_remove_ticker_sp50'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='sp500',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
