# Generated by Django 3.1.2 on 2020-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0020_ticker_sp500'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='treas',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='vix',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
