# Generated by Django 3.1.2 on 2020-12-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0021_auto_20201202_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='sp500',
            new_name='GSPC',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='treas',
            new_name='TNX',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='vix',
            new_name='VIX',
        ),
    ]
