# Generated by Django 3.1.2 on 2020-12-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0022_auto_20201202_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='TNX',
        ),
    ]
