# Generated by Django 3.1.2 on 2020-12-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0023_remove_ticker_tnx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='TNX',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
