# Generated by Django 3.1.2 on 2020-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0025_auto_20201209_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='res_vac',
            field=models.FloatField(),
        ),
    ]
