# Generated by Django 3.1.2 on 2021-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0026_auto_20201211_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='brent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='gold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='ixic',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
