# Generated by Django 3.1.2 on 2021-01-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0027_auto_20210103_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='brent',
            new_name='wti',
        ),
    ]
