# Generated by Django 3.1.2 on 2021-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0028_auto_20210103_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='rut',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
