# Generated by Django 3.0.1 on 2021-06-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybl', '0031_auto_20210610_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang_graphs',
            old_name='Java',
            new_name='res_vac',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='Javascript',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='Python',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='cpp',
        ),
        migrations.RemoveField(
            model_name='lang_graphs',
            name='php',
        ),
        migrations.AddField(
            model_name='lang_graphs',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='bpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybl.Bpost'),
        ),
    ]
